### ISSUE TITLE
Issues with chat when scaled

### ISSUE THREAD

**Issue by lilyheart** [killjoy1221/TabbyChat-2#11]
When using chat scaling (Options -> Multiplayer Settings -> Scale) various parts of the chat interface do not scale with the box.  

As discussed previous on IRC some scaling has been fixed.  Documenting here things that are still off:

- [x] Tab selection on the horizontal plane.
- [x] Link clicking on the horizontal and vertical plane.

**Comment by killjoy1221** [comment]
I fixed the tabs in killjoy1221/MnM-Utils@c6a9265bfc19e72517078167825eecf7be58d0b9

I still have to do the links.

**Comment by killjoy1221** [comment]
Should be fixed now. ef82793f3fee5d2ee0bd80fae31cb9ad089bf489

**Comment by lilyheart** [comment]
I rebuilt MnM-Utils again today just in case I missed something.  I verified the changes listed in that commit were in the files I cloned before the build.  They were and I'm still having the same issue regarding the tabs being off.

**Comment by killjoy1221** [comment]
Run this in cmd.

`gradlew clean build`

This will make sure that no old files are left behind.

**Comment by killjoy1221** [comment]
Are you still having issues with this?

**Comment by killjoy1221** [comment]
I'm closing this as fixed. if you still have issues, request it to be reopened.
